name: GitHub Actions Login
on: [push]
jobs:
  Explore-GitHub-Login:
    runs-on: ubuntu-latest
    steps:
        
      - name: Setup Azure SPN Certificate file inside the runner
        env:
          CERT: ${{ secrets.SPN }}
        run: |
          echo "$CERT" > file.pem      
      - name: Login to Azure
        run: |
          az login --service-principal -u ${{ secrets.SPN_ID }} -p file.pem --tenant ${{ secrets.TENTANT_ID }}

      - uses: azure/appservice-settings@v1
        with:
          app-name: 'skillathon2022api'
          #slot-name: 'staging'  # Optional and needed only if the settings have to be configured on the specific deployment slot
          app-settings-json: '${{ secrets.APP_SETTINGS }}'
          connection-strings-json: '${{ secrets.CONNECTION_STRINGS }}'
          general-settings-json: '{"alwaysOn": "false", "webSocketsEnabled": "true"}' #'General configuration settings as Key Value pairs'
        id: settings 

      - name: logout
        run: |
          az logout 
