name: Manual Run

on:
  workflow_dispatch:
    inputs:
      release-tag:
        type: string
        required: true

jobs:    
  print-input:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Print value
        run: echo ${{ github.event.inputs.release-tag }}
      - name: List Files
        shell: pwsh
        run: |
          .\list-files.ps1
